### ISSUE TITLE
[IDEA] Solution to the hardcoded destination problem

### ISSUE THREAD

**Issue by DeltaDizzy** [Mrcarrot1/Hyperdrive#1]
Have the module get a list of each planet, and use their FGI to get their displayName. Populate a UI with each planets name as a selectable button, and a "Warp" button at the bottom.

Feedback appreciated.

**Comment by Mrcarrot1** [comment]
I have been wanting to implement this exact idea for a while, but I have __no__ clue how to do UIs.

**Comment by DeltaDizzy** [comment]
Let me introduce you to the Unity manual.
https://docs.unity3d.com/540/Documentation/Manual/gui-Basics.html

**Comment by DeltaDizzy** [comment]
Ok so I've decided to do the ui. I'll probably get the display name and use a combination select/warp button with an extra confirmation window.
